# Parameters for framework
FRAME_HEIGHT: 400
FRAME_WIDTH: 400
LINE_WEIGHT: 3
CELL_WIDTH: 100
CELL_HEIGHT: 100
MARGIN_X: 50
MARGIN_Y: 60
NUM_ROWS: 3
NUM_COLS: 3
EMPTY_THRESHOLD: 0.15

# Colors
LINE_COLOR: [0, 0, 255] # Red
CIRCLE_COLOR: [255, 0, 0] # Blue
OVERLAY_COLOR: [0, 255, 0] # Green

# Parameters for circle detection using Hough transform
MINDIST: 40 # Minimum distance between the centers
PARAM1: 20 # Edge detection threshold
PARAM2: 20 # Circle detection threshold
MINRADIUS: 10 # Minimum radius
MAXRADIUS: 60 # Maximum radius
